### ISSUE TITLE
Build with NVIDIA cmake file broken on Lassen

### ISSUE THREAD

**Issue by tpatki** [LLNL/variorum#134]
The CUDA-cmake build for Lassen does not print out _IBMPOWER, and does not recognize **any** other IBM functionality. The `_IBMPOWER` data as well as setting power caps is broken in this build. The regular non-CUDA build does all of this correctly on Lassen, so it seems like we are not picking up the non-NVML components in the NVIDIA build for some reason. 

To be debugged later....

@rountree and I have both reproduced this. 

```
$ ./variorum-print-power-example 
_GPU_POWER_USAGE Host Socket Device Power
_GPU_POWER_USAGE lassen23 0 0 33.836002
_GPU_POWER_USAGE lassen23 0 1 35.850002
_GPU_POWER_USAGE lassen23 1 2 34.832002
_GPU_POWER_USAGE lassen23 1 3 35.375002
_GPU_POWER_USAGE lassen23 0 0 33.858002
_GPU_POWER_USAGE lassen23 0 1 35.850002
_GPU_POWER_USAGE lassen23 1 2 34.832002
_GPU_POWER_USAGE lassen23 1 3 35.375002


./variorum-set-node-power-limit-example 
No power limit specified...using default limit of 500W.
lassen23:/g/g90/patki1/src/var-clean/variorum/src/variorum/variorum.c:variorum_set_node_power_limit():223: _ERROR_VARIORUM_FEATURE_NOT_IMPLEMENTED: Feature not yet implemented or is not supported

_GPU_POWER_LIMIT Host: lassen23, Socket:0, Device ID: 0, Power limit: 300.000
_GPU_POWER_LIMIT Host: lassen23, Socket:0, Device ID: 1, Power limit: 300.000
_GPU_POWER_LIMIT Host: lassen23, Socket:1, Device ID: 2, Power limit: 300.000
_GPU_POWER_LIMIT Host: lassen23, Socket:1, Device ID: 3, Power limit: 300.000


$ ./variorum-get-node-power-json-example 
lassen23:/g/g90/patki1/src/var-clean/variorum/src/variorum/variorum.c:variorum_get_node_power_json():785: _ERROR_VARIORUM_FEATURE_NOT_IMPLEMENTED: Feature not yet implemented or is not supported
{}
lassen23:/g/g90/patki1/src/var-clean/variorum/src/variorum/variorum.c:variorum_get_node_power_json():785: _ERROR_VARIORUM_FEATURE_NOT_IMPLEMENTED: Feature not yet implemented or is not supported
```

**Comment by slabasan** [comment]
@tpatki Are you using one of the host-config files? Otherwise, could you please send me your CMakeCache.txt on quartz?

**Comment by tpatki** [comment]
Yes, using the `lassen-4.14.0-ppc64le-gcc@4.9.3-cuda@10.1.243.cmake` file. 

The `lassen-4.14.0-ppc64le-gcc@4.9.3.cmake` file works correctly as intended.

**Comment by tpatki** [comment]
Also, haven't tested this on quartz yet.

Here's the Lassen output with the non-CUDA cmake (`lassen-4.14.0-ppc64le-gcc@4.9.3.cmake`) file. 

```
$ ./variorum-print-power-example 
_IBMPOWER Host Socket PWRSYS PWRPROC PWRMEM PWRGPU Timestamp
_IBMPOWER lassen23 0 390 77 23 67 0.000019
_IBMPOWER lassen23 1 0 90 23 68 0.000065
_IBMPOWER lassen23 0 390 77 23 67 0.000110
_IBMPOWER lassen23 1 0 90 23 68 0.000139


$ ./variorum-set-node-power-limit-example 
No power limit specified...using default limit of 500W.
Changed node power cap to 500 W.

NOTE: 
  It may take 100-500ms for power cap to propagate out of band, so please
  verify again with dump_power_limits before setting the cap again.

_POWERCAP CurrentWatts MaxWatts MinWatts CPU_to_GPU_0 PSR CPU_to_GPU_8 PSR
_POWERCAP 3050 3050 500 100 100 


$ ./variorum-get-node-power-json-example 
{"hostname": "lassen23", "timestamp": 1597782111987690, "power_node": 391.0, "power_cpu_socket_0": 75.0, "power_mem_socket_0": 23.0, "power_gpu_socket_0": 66.0, "power_cpu_socket_1": 90.0, "power_mem_socket_1": 23.0, "power_gpu_socket_1": 67.0}
{"hostname": "lassen23", "timestamp": 1597782111987894, "power_node": 391.0, "power_cpu_socket_0": 75.0, "power_mem_socket_0": 23.0, "power_gpu_socket_0": 66.0, "power_cpu_socket_1": 90.0, "power_mem_socket_1": 23.0, "power_gpu_socket_1": 67.0}

```

**Comment by slabasan** [comment]
So I'm seeing that: 
`lassen-4.14.0-ppc64le-gcc@4.9.3-cuda@10.1.243.cmake` <-- NVIDIA ONLY
`lassen-4.14.0-ppc64le-gcc@4.9.3.cmake` <-- IBM ONLY

In your tests above, are you modifying `lassen-4.14.0-ppc64le-gcc@4.9.3-cuda@10.1.243.cmake` to turn on `VARIORUM_WITH_IBM`?

**Comment by slabasan** [comment]
I think what you want is the host-config file in #121. This was how I configured an NVIDIA and IBM build on lassen (a few months ago), so I haven't had a chance to check that the paths are still valid.

**Comment by tpatki** [comment]
> In your tests above, are you modifying lassen-4.14.0-ppc64le-gcc@4.9.3-cuda@10.1.243.cmake to turn on VARIORUM_WITH_IBM and seeing then seeing the errors?

I was not. Let me try....

**Comment by slabasan** [comment]
@tpatki Any updates on this? Were you able to build for NVIDIA+IBM using the CMake file?

**Comment by slabasan** [comment]
@tpatki Any updates here?

**Comment by slabasan** [comment]
The referenced cmake host config file works successfully for building variorum for IBM and Nvidia.
