### ISSUE TITLE
PlatformIO APIs

### ISSUE THREAD

**Issue by rountree** [LLNL/variorum#14]
Add PlatformIO APIs found in GEOPM.  See https://github.com/geopm/geopm

PlatformIO uses a "signal/control" interface rather than a collection of function calls.  There are advantages to each.  I'd like Variorum to be able to be used as a drop-in replacement for PlatformIO.  Eventually, the two projects might merge.

**Comment by tpatki** [comment]
I believe we want to interface with PlatformIO through JSON.

**Comment by amarathe84** [comment]
@tpatki I think the task outlined here is different from that of interfacing Variorum with PlatformIO. This task is about supporting in Variorum the public-facing APIs that PlatformIO provides (signal/control). We haven't scoped out how we'd provide those APIs with the JSON interface under-the-hood (for platform neutrality) yet. As such I'd suggest to create a separate issue to track the effort on interfacing Variorum with PlatformIO.   Comments?

**Comment by tpatki** [comment]
I am not sure if we want to pursue the original task of adding PlatformIO API to Variorum -- I believe we had decided against that a while ago, but it is possible that I remember incorrectly. What do @slabasan and @rountree think? 

Our goal is to support GEOPM, certainly: but I am not sure if the suggestion of doing so by adding PlatformIO APIs in Variorum is the preferred way. I believe we need to decide on *how* to support GEOPM: either through the JSON interface, or through adding PlatformIO APIs to Variorum. I prefer the former. Thoughts?

**Comment by tpatki** [comment]
Closing this issue, and opening a new one, based on our discussion today.
