### ISSUE TITLE
Implement PowerAPI interfaces

### ISSUE THREAD

**Issue by rountree** [LLNL/variorum#15]
The PowerAPI standard specifies several node-level interfaces.  While a reference implementation exists, I would like to have Variorum become a second implementation than can offer greater hardware coverage.

**Comment by tpatki** [comment]
This can be a stretch goal for Milestone v.0.6.0, so that it stays on our priority list.

**Comment by sanmai-NL** [comment]
Searching for PowerAPI, multiple systems and sources appear. Do you mean https://powerapi.sandia.gov/?

**Comment by tpatki** [comment]
Hi @sanmai-NL, yes. It started at Sandia, but is now a community wide effort. I believe the latest website is the GitHub.io website. You can also reach out to Ryan Grant (https://www.ece.queensu.ca/people/R-Grant/madev-faculty-page.html, @regrant) for more details. 
- https://github.com/pwrapi 
- https://pwrapi.github.io

**Comment by tpatki** [comment]
The initial integration is here: https://github.com/LLNL/variorum-integrations/pull/1
We will add this to documentation in a separate upcoming milestone.
