### ISSUE TITLE
hardware docs issues

### ISSUE THREAD

**Issue by loveshack** [LLNL/variorum#152]
I haven't gone through the doc in detail, but I noticed these:
HWArchitectures.rst only lists Intel and IBM, not AMD and GPU (though I guess "GPU" should be "Nvidia").
BuildingVariorum.rst lists cmake options VARIORUM_AMD etc., which should be VARIORUM_WITH_AMD etc.
Also, not a bug, but it would probably be helpful to have an overview for AMD and GPU as for Intel and IBM.

**Comment by slabasan** [comment]
Hi @loveshack, thanks for the feedback! Yes, our documentation is due for an update. Our main `dev` branch has support for several Intel CPU architectures, IBM Power9 CPU, and Nvidia Volta GPUs. We do have a CMake variable for `VARIORUM_WITH_AMD` (will make a note to update that variable), which does nothing so far. We do have plans to add support for AMD (and more architectures to come), but this is still WIP. If you have any questions or are interested in contributing, please let us know!

**Comment by loveshack** [comment]
Ah, I didn't realize AMD does nothing.  I found the different in flags
trying to build for Sierra-like nodes with the readthedocs instructions,
when it failed trying to build Intel stuff.  That won't affect many
users anyway.

I should have said I was using the current release.

**Comment by slabasan** [comment]
Yes, our default build targets Intel platforms. This is mostly for legacy reasons -- most of the systems where we've been using variorum have been Intel, but I suspect this may change going forward. For sierra-like nodes, we have a host config file for Livermore's lassen system, which is similar to Sierra, and could also be used as a reference for the different flags.

**Comment by slabasan** [comment]
Hi @loveshack, closing this issue, but please let us know if there's other information you'd like to see in our docs.
