### ISSUE TITLE
Journal of Open Source Software submission

### ISSUE THREAD

**Issue by rountree** [LLNL/variorum#16]
Submission guidelines here: https://joss.readthedocs.io/en/latest/submitting.html#no-submission-fees

About the journal:  https://joss.theoj.org/about#costs

Note that they do not accept "minor 'utility' packages, such as 'thin' API clients".  We might want to get a few more ports completed before submission.

**Comment by tpatki** [comment]
I believe we are going to target a different conference/platform given how Variorum has evolved. I am closing this issue, @slabasan @rountree .
