### ISSUE TITLE
hwloc dependency version requirement in Spack package

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/variorum#180]
Does `variorum` specifically require `hwloc 1.11.9`, or are newer versions OK ?

I'm asking because the Spack package for it specifically pins it to `hwloc 1.11.9`.
https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/variorum/package.py

 If this is not a hard constraint then I will relax it in the Spack package.

**Comment by tpatki** [comment]
@eugeneswalker : Any version of `hwloc` should be fine, it is not a hard constraint and should be okay to relax it in the Spack package. Sorry about the delay in responding, but I believe this is already fixed in the spack package.
