### ISSUE TITLE
variorum-cap-and-verify-node-power-limit-example.c is not included in CMakeList.

### ISSUE THREAD

**Issue by chaz-browne** [LLNL/variorum#257]
The "cap and verify" c file is not included in the CMakeList file in the examples directory. After including the file and building the project, I received the following error.  
```/home/chazakilbrowne/variorum/src/examples/variorum-cap-and-verify-node-power-limit-example.c: In function ‘main’:
/home/chazakilbrowne/variorum/src/examples/variorum-cap-and-verify-node-power-limit-example.c:56:11: warning: implicit declaration of function ‘variorum_cap_and_verify_node_power_limit’; did you mean ‘variorum_cap_best_effort_node_power_limit’? [-Wimplicit-function-declaration]
   56 |     ret = variorum_cap_and_verify_node_power_limit(node_pow_lim_watts);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |           variorum_cap_best_effort_node_power_limit
```
Was this expected to work?

**Comment by tpatki** [comment]
No, this has been deprecated (set-and-verify, cap-and-verify), see here: https://github.com/LLNL/variorum/issues/208. 

Looks like there is a lingering legacy example that we need to delete from the repository, thanks for catching that.

**Comment by rountree** [comment]
That's easy enough.  @chaz-browne I'll walk you through this on Monday if nobody else gets to it first.  @tpatki thanks for the quick reply!

**Comment by tpatki** [comment]
Thanks @rountree ! Looks like I had deleted the associated example from the tests with my old PR (#214), but not from examples directory. My bad for not catching it sooner -- thank you for finding this!

I might get to this sooner (before Monday, I mean) as the deprecation of this API is part of the current release.

**Comment by tpatki** [comment]
Tracking the same issue of deprecating `set_and_verify` (#208), also need to update `variorum/variorum.f90`.
