### ISSUE TITLE
Duplicate astyle formatting scripts?

### ISSUE THREAD

**Issue by rountree** [LLNL/variorum#263]
`./src` contains both `astyle-format.sh` and `check-code-format.sh`.  The former is used in both `github-actions.yml` and `.gitlab-ci.yml`.  The later isn't mentioned anywhere else in the codebase.  The scripts are nearly identical (the `astyle` command takes the same parameters) but not quite.

Is the second script intended for use by developers?  They both have the same bash-5.0-quoting bug, so if we want to keep two scripts I'd like to do a bit of refactoring.

**Comment by slabasan** [comment]
This is correct, the `astyle-format.sh` is designed to be used by the CI (errors if any files needs formatting, but does not actually change any of the files), and `check-code-format.sh` is for developers to check their code locally (formats files as needed and prints out whether the file is formatted or not). Yes, please feel free to refactor as needed!
