### ISSUE TITLE
Multiple definitions of m_hostname and m_num_package for ARM

### ISSUE THREAD

**Issue by patricoferris** [LLNL/variorum#276]
Hi :))

First of all, thank you for this great library!

I'm currently writing [OCaml bindings for the library](https://github.com/patricoferris/ocaml-variorum). The build process is quite specific to OCaml and that package in particular (for example it also wraps hwloc and jansson). The library is tested by submitting it to the [OCaml-CI](https://github.com/ocurrent/ocaml-ci) build cluster which tests on multiple platforms including ARM.

It seems, although I am not a C expert, that the ARM backend is experiencing similar problems to those seen in #216? I've added the failure log and success log to [this gist](https://gist.github.com/patricoferris/ccd0e78945cb466a8b7eca9e92f8d221) (again the logs might look a bit strange because they're wrapped in the OCaml build tool). The [CI run is here](https://github.com/patricoferris/ocaml-variorum/runs/7119762194). The build was successful after applying https://github.com/patricoferris/variorum/commit/45a0d72b2742ddee643c1489556177352403e473. I thought I would open an issue first in case I was doing something incorrect.

Thanks again.

**Comment by slabasan** [comment]
Hi @patricoferris, thank you for reporting this issue! Yes, I would agree we have the same issue here. Would you mind pushing up your fix as a PR? We greatly appreciate it!

**Comment by tpatki** [comment]
@patricoferris Thank you so much for writing the OCaml bindings for Variorum! We would like to collaborate with you as well, so we can support and make these bindings available to our other users. We are also very interested in hearing about how you're using Variorum, your power management use case, and what features we could add to support them. Maybe touching base over a call would be helpful -- let us know if you are open to this, and we can go from there.

**Comment by patricoferris** [comment]
Hi both, thanks for the warm welcome !

> Would you mind pushing up your fix as a PR? We greatly appreciate it!

Yep, the PR is open.

> We are also very interested in hearing about how you're using Variorum, your power management use case, and what features we could add to support them. Maybe touching base over a call would be helpful -- let us know if you are open to this, and we can go from there.

That would be great! Maybe the best next step would be to arrange a call over email? If that works for you please do reach out, my email in on my Github profile :))

**Comment by tpatki** [comment]
Awesome, thanks @patricoferris !
It is the long weekend here in the US, so I will send out an email on Tuesday morning to set up a call. Have a lovely weekend!
