### ISSUE TITLE
Could not open any valid MSR module for device error

### ISSUE THREAD

**Issue by wadudmiah** [LLNL/variorum#303]
Hi,

I am trying to run the simple example code at https://variorum.readthedocs.io/en/latest/Examples.html, but I am getting the following error:

```
_LOG_VARIORUM_ENTER:/home/admwm1/variorum/src/variorum/variorum.c:variorum_print_verbose_power_limit::180
Intel Model: 0x55
cyan52.cluster.local:/home/admwm1/variorum/src/variorum/msr/msr_core.c:init_msr():442: _ERROR_VARIORUM_RAPL_INIT: Could not open file for device 0
cyan52.cluster.local:/home/admwm1/variorum/src/variorum/msr/msr_core.c:init_msr():442: _ERROR_VARIORUM_RAPL_INIT: Could not open file for device 0
cyan52.cluster.local:/home/admwm1/variorum/src/variorum/msr/msr_core.c:init_msr():448: _ERROR_VARIORUM_RAPL_INIT: Could not open any valid MSR module for device 0
cyan52.cluster.local:/home/admwm1/variorum/src/variorum/config_architecture.c:variorum_enter():71: _ERROR_VARIORUM_RAPL_INIT: Cannot set function pointers
Print verbose power limit failed!

```
This is the content of the `/dev/cpu` directory:
```
# ls /dev/cpu/
0  10  12  14  16  18  2   21  23  25  27  29  30  32  34  36  38  4  6  8  microcode      msr_batch
1  11  13  15  17  19  20  22  24  26  28  3   31  33  35  37  39  5  7  9  msr_allowlist
```
and likewise for the `/dev/cpu/0` directory:
```
# ls /dev/cpu/0
cpuid  msr  msr_safe
```
I have followed the instructions at https://github.com/LLNL/msr-safe to install MSR. Let me know if you require any further information - 
thanks in advance.

Regards,

**Comment by tpatki** [comment]
Hi @wadudmiah : Just to ensure it is not a permissions issue, can you send us an output of `ls -ltr /dev/cpu/msr_allowlist` and `ls -ltr /dev/cpu/0`? Also, to ensure that we support the architecture, could you also send the output of `lscpu`?

**Comment by tpatki** [comment]
Hi @wadudmiah : just following up on this -- were you able to get the Variorum example to work? How can we help?

**Comment by tpatki** [comment]
Hi @wadudmiah : just checking in. Were you able to get Variorum to build and the example to work?

**Comment by tpatki** [comment]
Closing this issue, we can reopen when @wadudmiah responds and confirms this is stick a problem.
