### ISSUE TITLE
Refactor Intel MSR configuration

### ISSUE THREAD

**Issue by rountree** [LLNL/variorum#343]
Our current best-practice for adding new functionality to Intel architectures requires an onerous search through Volume 4 to determine whether the documentation in Volume 3B is relevant, and from there write code that has only been proven to exist on that particular df_dm.  

I think this can be made scalable with two pieces of information:  a map of df_dms to the volume 4 tables they use, and a reverse of that map that shows which df_dms are affected by that table.  I've generated both of these.

Given that, I'm hoping to be able to add information about how individual MSRs have changed over time.  For example, MSR_DRAM_POWER_LIMIT is mentioned in tables 2-23, 2-26, 2-32, 2-36 and 2-50.  The first four of those tables describe the same interface; table 2-50 describes a significantly different interface.  Knowing this, writing a function that relies only on MSR_DRAM_POWER_LIMIT for any df_dm that uses tables 2-23, 2-26, 2-32 and 2-36 but does not include 2-50 should work on all df_dms that meet those conditions.  A second version of that function for df_dms that rely on 2-50 complete the coverage (which happens to be a single df_dm:  06_55H).

Given that there are 32 unique df_dms for non-Atom, non-Phi architectures since Sandy Bridge, keeping separate `*.[ch]` files for each will probably run into scalability issues.  I haven't been able to think of a good naming scheme and might just fall back to "v1," "v2," etc.  Or perhaps it might be better to have a single kind of function per file.

One of the risks to this approach is the table numbers can change silently with new versions of the SDM.  With Atom no longer under development this is less of an issue, but we may need another level of indirection to refer to table numbers that can move around.  No good ideas how to handle that yet.

Next steps are porting existing code to this setup and we'll see how it goes.

**Comment by slabasan** [comment]
Closing now, revisit after possible msr-genie redesign.
