### ISSUE TITLE
Provide shim library for CI/CD

### ISSUE THREAD

**Issue by rountree** [LLNL/variorum#374]
For architectures that use system calls directly (rather than external libraries), allow interception of those system calls in order to replay canned data.  Ultimately, this capability should allow for testing code for all architectures on a single CI/CD machine.

Note that this will require capture and playback for CPUID and hwloc as well.

**Comment by sanmai-NL** [comment]
@tpatki I'm curious in which PR this was implemented.

**Comment by tpatki** [comment]
This has not been implemented. There's a discussion with potential ideas captured here: https://github.com/LLNL/variorum/discussions/402. We will not be implementing this at our end.
