### ISSUE TITLE
Multiple function definition error when attempting to build ARM CPU+NVIDIA GPU support  

### ISSUE THREAD

**Issue by amarathe84** [LLNL/variorum#376]
I'm seeing 'multiple function definition' error when I attempt to build Variorum after enabling support for both ARM CPU and NVIDIA GPU on nvhpc1 system: 

```
...
[ 11%] Building C object variorum/CMakeFiles/variorum.dir/Nvidia_GPU/config_nvidia.c.o
[ 12%] Building C object variorum/CMakeFiles/variorum.dir/ARM/config_arm.c.o
/home/marathe1/software/varioum-intel-gpu/src/variorum/ARM/config_arm.c: In function ‘set_arm_func_ptrs’:
/home/marathe1/software/varioum-intel-gpu/src/variorum/ARM/config_arm.c:45:5: warning: implicit declaration of function ‘init_arm’; did you mean ‘initNVML’? [-Wimplicit-function-declaration]
     init_arm();
     ^~~~~~~~
     initNVML
[ 13%] Linking Fortran shared library libvariorum.so
ARM/CMakeFiles/variorum_arm.dir/power_features.c.o: In function `get_power_data':
/home/marathe1/software/varioum-intel-gpu/src/variorum/ARM/power_features.c:92: multiple definition of `get_power_data'
Nvidia_GPU/CMakeFiles/variorum_nvidia.dir/power_features.c.o:/home/marathe1/software/varioum-intel-gpu/src/variorum/Nvidia_GPU/power_features.c:52: first defined here
ARM/CMakeFiles/variorum_arm.dir/power_features.c.o: In function `get_thermal_data':
/home/marathe1/software/varioum-intel-gpu/src/variorum/ARM/power_features.c:182: multiple definition of `get_thermal_data'
Nvidia_GPU/CMakeFiles/variorum_nvidia.dir/power_features.c.o:/home/marathe1/software/varioum-intel-gpu/src/variorum/Nvidia_GPU/power_features.c:85: first defined here
ARM/CMakeFiles/variorum_arm.dir/power_features.c.o: In function `get_clocks_data':
/home/marathe1/software/varioum-intel-gpu/src/variorum/ARM/power_features.c:254: multiple definition of `get_clocks_data'
Nvidia_GPU/CMakeFiles/variorum_nvidia.dir/power_features.c.o:/home/marathe1/software/varioum-intel-gpu/src/variorum/Nvidia_GPU/power_features.c:153: first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [variorum/CMakeFiles/variorum.dir/build.make:205: variorum/libvariorum.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:338: variorum/CMakeFiles/variorum.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

Relevant parts of the CMake config file: 

```
 ...

set(VARIORUM_WITH_ARM_CPU ON CACHE BOOL "")
set(VARIORUM_WITH_NVIDIA_GPU ON CACHE BOOL "")
...
```

I think the error occurs because the low-level functions for each platform (ARM and NVIDIA in this case) have the same names (e.g. get_power_data). Because C doesn't support namespaces, function name collision from the object files of enabled platforms occurs when CMake attempts to link them to build libvariorum.so. One way to resolve this issue would be to prefix them [vendor]_[platform] to avoid name collision. 

I'm mildly concerned about the warning about implicit declaration of function ‘init_arm’. It appears to be independent from this specific issue and may be handled separately.

**Comment by tpatki** [comment]
@amarathe84 

Thanks for catching this: didn't show up in our IBM + NVIDIA or Intel + Intel DGPU or AMD + AMD GPU etc tests. 

I am guessing the `init_arm` and `init_NVML` issue is also related to the build: the `init_arm` is defined in `power_features.h` under the ARM code, and a header with the same name exists in the NVIDIA codebase as well, so it is having trouble pulling both headers with the same name in and finding definitions for `init_arm` I think. 

Looks like a name collision, but I'm very surprised this hasn't shown up elsewhere when we tested (eg Tioga, where we also have `power_features.h` in the CPU and GPU code, I think), so I wonder if there's something small we're missing during the build.

What's the `nvhpc1` system configuration and how can I access it?

**Comment by amarathe84** [comment]
I think it didn't happen on Tioga because the low-level function names supported by the AMD CPU and GPU ports don't overlap. Same situation with the IBM P9 and NVIDIA ports. I'm not sure if we've tried the Intel CPU + DGPU multiplatform build. 

nvhpc1 is accessible through cztb2. 

+1 on the init_arm and init_NVML -- I now think that warning is part of the same multi-platform build issue.
