### ISSUE TITLE
Create a design document for the shim library

### ISSUE THREAD

**Issue by rountree** [LLNL/variorum#383]
The number of potential uses for the shim library continues to grow, which unfortunately has led to quite a bit of avoidable rework.  Barry could stand a document that lays out what the shim library will do and the steps needed to get it there.

**Comment by sanmai-NL** [comment]
Who's Barry? It's an OSS product 😉

**Comment by tpatki** [comment]
Closing the associated issue around shim layer. We moved this to the Github Discussions page.
