### ISSUE TITLE
Memory leak in JSON examples

### ISSUE THREAD

**Issue by amarathe84** [LLNL/variorum#398]
The APIs `variorum_get_node_power_json(char **)` and `variorum_get_node_power_domain_info_json(char **)` expect a char ** pointer into which the `json_dumps()` eventually returns an allocated char array. But before passing them to the JSON APIs, both JSON examples assign a block of memory to the pointers that are re-assigned to another check of memory returned by `json_dumps()` in the architecture-specific implementations of  `*_get_node_power_json()` and `*_get_node_power_domain_info_json()`.

The examples should remove the `malloc()` calls that cause the memory leak.

**Comment by tpatki** [comment]
@amarathe84  Good catch! You're right, the `json_object()` and the `json_dumps()` calls which are internal to the implementation of the function should take care of the allocation of memory. I think we may have this in a few more places, let me go look where else we need to fix this.

**Comment by tpatki** [comment]
Need to fix in the following places: 

- Caliper port: https://github.com/LLNL/Caliper/blob/f6eee70a17e7191f143e9d3b1ab3c4ca8ed2aa10/src/services/variorum/Variorum.cpp#L40

- LDMS port: https://github.com/ovis-hpc/ovis/blob/7b372c6c113ec487de8c386689e854d2a05d7299/ldms/src/contrib/sampler/variorum_sampler/variorum_sampler.c#L112 

Flux port is correct (haven't pushed it upstream yet). 
Docs are correct here: https://variorum.readthedocs.io/en/latest/VariorumTools.html
