### ISSUE TITLE
Docs update: Add 2023 tutorial links.

### ISSUE THREAD

**Issue by tpatki** [LLNL/variorum#406]
Power Management on Exascale Platforms with Variorum (Tutorial) 
[https://uoregon.zoom.us/rec/share/d1DQsA350JJrU0hVbQf401YOm5p4cLbKIN29rBv9_4Blp2sCjV-SKqXXEwDQa284.c2bhMxzM9Ia2qoDM](https://urldefense.us/v3/__https://uoregon.zoom.us/rec/share/d1DQsA350JJrU0hVbQf401YOm5p4cLbKIN29rBv9_4Blp2sCjV-SKqXXEwDQa284.c2bhMxzM9Ia2qoDM__;!!G2kpM7uM-TzIFchu!mL-Kj-KjQU_X5XVuYWQJPn6LFB_NqE-i4cKVvIMji0tvNATI-USgqkrRomCyxRa_$) 

Power Management on Exascale Platforms with Variorum (Tutorial) (Second recording)
[https://uoregon.zoom.us/rec/share/K6rSbJeeW3R0wPndnspRJ3a-_ZJ_TywH__2fGJKW3h6TutWTac77RawRmr9ypCWV.EvsYnRIV7jy8pAdK](https://urldefense.us/v3/__https://uoregon.zoom.us/rec/share/K6rSbJeeW3R0wPndnspRJ3a-_ZJ_TywH__2fGJKW3h6TutWTac77RawRmr9ypCWV.EvsYnRIV7jy8pAdK__;!!G2kpM7uM-TzIFchu!mL-Kj-KjQU_X5XVuYWQJPn6LFB_NqE-i4cKVvIMji0tvNATI-USgqkrRovFySQie$) 

These will expire in an year, Feb 2024. So we need to remember to remove them, or download and create other links that are shareable :)

**Comment by sanmai-NL** [comment]
What's the reason to list two recordings?

**Comment by slabasan** [comment]
There are two recordings, one for the first session and another for the second session of the tutorial. These were held in February 2023 as part of the ECP Tutorial Series.

Variorum is a production-grade, open-source, vendor-neutral software infrastructure for exposing low-level control and monitoring of a system’s underlying hardware features. This Variorum Tutorial will consist of two modules, each of 1.5 hours each.

Module 1
* Focusing on supporting vendor-neutrality, building and utilizing Variorum, and low-level power knobs for supported architectures (AMD, Intel, IBM, ARM, NVIDIA, Intel and AMD GPUs)
* Monday, Feb 6 2023, 8:00am-9:30am PT (11:00am-12:30pm ET)

Module 2
* Focusing on Variorum integrations (with LDMS, GEOPM/NRM, Flux, Kokkos, Caliper)
* Monday, Feb 6 2023, 9:45am-11:15am PT (12:45pm-2:15pm ET)

**Comment by sanmai-NL** [comment]
So two modules, happening to be between two recordings. Got it.

**Comment by slabasan** [comment]
Yes, that's correct. I think it was meant to be 1 recording, but our meeting was disconnected in the middle, so we ended up with separate recordings for the modules.

**Comment by sanmai-NL** [comment]
> Power Management on Exascale Platforms with Variorum (Tutorial) [https://uoregon.zoom.us/rec/share/d1DQsA350JJrU0hVbQf401YOm5p4cLbKIN29rBv9_4Blp2sCjV-SKqXXEwDQa284.c2bhMxzM9Ia2qoDM](https://urldefense.us/v3/__https://uoregon.zoom.us/rec/share/d1DQsA350JJrU0hVbQf401YOm5p4cLbKIN29rBv9_4Blp2sCjV-SKqXXEwDQa284.c2bhMxzM9Ia2qoDM__;!!G2kpM7uM-TzIFchu!mL-Kj-KjQU_X5XVuYWQJPn6LFB_NqE-i4cKVvIMji0tvNATI-USgqkrRomCyxRa_$)
> 
> Power Management on Exascale Platforms with Variorum (Tutorial) (Second recording) [https://uoregon.zoom.us/rec/share/K6rSbJeeW3R0wPndnspRJ3a-_ZJ_TywH__2fGJKW3h6TutWTac77RawRmr9ypCWV.EvsYnRIV7jy8pAdK](https://urldefense.us/v3/__https://uoregon.zoom.us/rec/share/K6rSbJeeW3R0wPndnspRJ3a-_ZJ_TywH__2fGJKW3h6TutWTac77RawRmr9ypCWV.EvsYnRIV7jy8pAdK__;!!G2kpM7uM-TzIFchu!mL-Kj-KjQU_X5XVuYWQJPn6LFB_NqE-i4cKVvIMji0tvNATI-USgqkrRovFySQie$)
> 
> These will expire in an year, Feb 2024. So we need to remember to remove them, or download and create other links that are shareable :)

The two modules are listed in decreasing order of module number. I suspect that was unintended.
