### ISSUE TITLE
Linker Errors Due to Multiple Variable Definitions in 'nvidia_gpu_power_features.h' in newer version of gcc

### ISSUE THREAD

**Issue by kulnaman** [LLNL/variorum#463]
### Description:

When compiling the project, I encountered linker errors related to multiple definitions of certain variables. The affected variables are: m_total_unit_devices, m_unit_devices_file_desc, m_gpus_per_socket, and m_hostname.

The error messages in question:
```
/usr/bin/ld: ../variorum/libvariorum.so: undefined reference to `m_total_unit_devices'
/usr/bin/ld: ../variorum/libvariorum.so: undefined reference to `m_unit_devices_file_desc'
/usr/bin/ld: ../variorum/libvariorum.so: undefined reference to `m_gpus_per_socket'
/usr/bin/ld: ../variorum/libvariorum.so: undefined reference to `m_hostname'
```
### Possible Cause:
It seems that the aforementioned variables are declared in the `nvidia_gpu_power_features.h` header without the extern keyword, and included in multiple source files. This leads to each source file getting its own copy of the variable, causing linker errors when these object files are being combined.

Expected Behavior:
The project should compile and link without any errors.

Steps to Reproduce:
Clone the latest version of the repository.
Run the build commands (e.g., mkdir build && cd build && cmake .. && make).
Observe the linker errors.

### Tested On:

Nvidia Titan XP 
Intel Broadwell

**Comment by tpatki** [comment]
Closed with #465.
